### ISSUE TITLE
could not find commit hash for HEAD

### ISSUE THREAD

**Issue by baermatthias** [openlayers/create-ol-app#2]
- solved

**Comment by Chris-GIS** [comment]
i got the same problem - how did you solve it? regards chris

**Comment by baermatthias** [comment]
In my case git for windows was missing. After installing git and reboot it worked

**Comment by Chris-GIS** [comment]
Big thank you - that worked for me (using the GIT Cmd to create the ol-app) :)

**Comment by debaser75** [comment]
Thanks for posting this. This issued killed a good amount of time until I finally ran across this discussion. Installing git solved this problem for me as well (Windows 10). Does anyone know who to contact to have this information added to [this page on the OL site](https://openlayers.org/en/latest/doc/tutorials/bundle.html)? Same for [this page](https://www.npmjs.com/package/create-ol-app). It could be just one sentence: "If you receive an error message along the lines of 'Could not find commit hash for HEAD', make sure that git is properly installed on your system."  That would have saved me a lot of time. Just a suggestion. Thanks to all in the OL community for producing such amazing, free software.

**Comment by tschaub** [comment]
Thanks for the suggestion, @debaser75.  If you could open an issue on https://github.com/openlayers/openlayers/issues with this detail, that will be something that someone can follow up on.  I’ll reopen this issue as well as a reminder to update the docs here.
